name: di
description: Dependency Injection layer for managing dependencies between layers
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  data:
    path: ../data
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
